#CONFIG_FILE



# CLIMATE_DATA = "meteorology/climate/now/data/10m-0-20000-0-11683-20241002.json"
# CLIMATE_METADATA = "meteorology/climate/now/metadata/meta1-20240930.json"
# WEATHER_ALERTS = "meteorology/weather/alerts/cap/alert_cap_010823.xml"
# WEATHER_RADAR_COMPOSITE_ECHOTOP = "meteorology/weather/radar/composite/echotop/hdf5/T_PADV23_C_OKPR_20240925150500.hdf"
# WEATHER_NWP_ALADIN = "meteorology/weather/nwp_aladin/CZ_1km/00/ALADCZ1K4opendata_2024100200_SURFPREC_TOTAL.grb.bz2"


DOMAIN00 = "https://opendata.chmi.cz/meteorology/weather/nwp_aladin/CZ_1km/00/ALADCZ1K4opendata_"
DOMAIN12 = "https://opendata.chmi.cz/meteorology/weather/nwp_aladin/CZ_1km/12/ALADCZ1K4opendata_"



ALADIN_ATTRIBUTES = {
"MSLPRESSURE" : "MSLPRESSURE",
"CLSTEMPERATURE" : "CLSTEMPERATURE", 
"CLSHUMI_RELATIVE" : "CLSHUMI_RELATIVE",
"CLSWIND_SPEED" : "CLSWIND_SPEED",
"CLSWIND_DIREC" : "CLSWIND_DIREC",
"CLSU_RAF_MOD_XFU" : "CLSU_RAF_MOD_XFU",
"CLSV_RAF_MOD_XFU" : "CLSV_RAF_MOD_XFU",
"SURFNEBUL_BASSE" : "CLSV_RAF_MOD_XFU",
"SURFNEBUL_MOYENN" : "SURFNEBUL_MOYENN",
"SURFNEBUL_HAUTE" : "SURFNEBUL_HAUTE",
"CLS_VISICLD" : "CLS_VISICLD",
"CLS_VISIPRE" : "CLS_VISIPRE",
"SURFRAINFALL" : "SURFRAINFALL",
"SURFSNOWFALL" : "SURFSNOWFALL",
"SURFPREC_TOTAL" : "SURFPREC_TOTAL",
"PRECIP_TYPE" : "PRECIP_TYPE",
"PRECIP_TYPESEV" : "PRECIP_TYPESEV",
"SURFCAPE_POS_F00" : "SURFCAPE_POS_F00",
"SURFCIEN_POS_F00" : "SURFCIEN_POS_F00",
"SURFDIAG_FLASH" : "SURFDIAG_FLASH",
"MAXSIM_REFLECTI" : "MAXSIM_REFLECTI"
}